version: '3.8'

services:
  ventas:
    image: 068461358306.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
    container_name: ventas-api
    restart: always
    environment:
      DB_ENDPOINT: 10.0.154.139
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"

  despachos:
    image: 068461358306.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest
    container_name: despachos-api
    restart: always
    environment:
      DB_ENDPOINT: 10.0.154.139
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8081:8081"