version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopsdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persistencia de datos local
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ventas:
    image: ventas-api:local
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: ventas-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - app-network

  despachos:
    image: despachos-api:local
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: despachos-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: devopsdb
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    image: frontend-app:local
    build:
      context: ./front_despacho
    container_name: frontend-app
    restart: always
    depends_on:
      - ventas
      - despachos
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge